# Generated by Django 4.0.4 on 2022-06-01 22:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MaxValueValidator(9999.99), django.core.validators.MinValueValidator(0)], verbose_name='$'),
        ),
    ]
