# Generated by Django 4.0.4 on 2022-06-01 22:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_bid_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MaxValueValidator(9999.99), django.core.validators.MinValueValidator(0)], verbose_name='Bid: $'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(max_length=500, null=True, verbose_name='Comment'),
        ),
    ]
